// Source of truth for the name library. The frontend fetches this
// from GET /api/names so both sides always agree on names + meanings.

const NAME_DB = [
  // --- Prophets & figures named in the Qur'an ---
  { name: "Adam", arabic: "آدَمُ", meaning: "Father of Mankind, the First Human created by Allah" },
  { name: "Luqman", arabic: "لُقْمَانُ", meaning: "The Wise Man, Blessed with Wisdom" },
  { name: "Muhammad", arabic: "مُحَمَّدٌ", meaning: "Praiseworthy, One who is constantly praised" },
  { name: "Muhammed", arabic: "مُحَمَّدٌ", meaning: "Praiseworthy, One who is constantly praised" },
  { name: "Mohammed", arabic: "مُحَمَّدٌ", meaning: "Praiseworthy, One who is constantly praised" },
  { name: "Ibrahim", arabic: "إِبْرَاهِيمُ", meaning: "Father of Nations, the Friend of Allah (Khalilullah)" },
  { name: "Ismail", arabic: "إِسْمَاعِيلُ", meaning: "God Will Hear — son of Ibrahim, Prophet of Allah" },
  { name: "Ishaq", arabic: "إِسْحَاقُ", meaning: "He Will Laugh — Prophet Isaac, son of Ibrahim" },
  { name: "Yaqub", arabic: "يَعْقُوبُ", meaning: "Supplanter, One Who Follows — Prophet Jacob" },
  { name: "Yusuf", arabic: "يُوسُفُ", meaning: "God Increases, the Most Beautiful One" },
  { name: "Musa", arabic: "مُوسَى", meaning: "Drawn Out of Water — the Prophet Moses" },
  { name: "Harun", arabic: "هَارُونُ", meaning: "The Exalted One — Prophet Aaron, brother of Musa" },
  { name: "Dawud", arabic: "دَاوُودُ", meaning: "Beloved — the Prophet David" },
  { name: "Sulaiman", arabic: "سُلَيْمَانُ", meaning: "Man of Peace — the Prophet Solomon, given dominion over jinn, birds and wind" },
  { name: "Yahya", arabic: "يَحْيَى", meaning: "He Shall Live — the Prophet John" },
  { name: "Zakariyya", arabic: "زَكَرِيَّا", meaning: "Remembrance of Allah — father of Prophet Yahya" },
  { name: "Isa", arabic: "عِيسَى", meaning: "The Prophet Jesus, son of Maryam, given the Injeel" },
  { name: "Nuh", arabic: "نُوحٌ", meaning: "Rest, Comfort — the Prophet Noah" },
  { name: "Idris", arabic: "إِدْرِيسُ", meaning: "The Studious Interpreter — an early Prophet of Allah, raised to a high station" },
  { name: "Hud", arabic: "هُودٌ", meaning: "Prophet sent to the people of 'Ad, who called them to worship Allah alone" },
  { name: "Salih", arabic: "صَالِحٌ", meaning: "Righteous, Pious — Prophet sent to the people of Thamud" },
  { name: "Shuayb", arabic: "شُعَيْبٌ", meaning: "Prophet sent to the people of Madyan, known for honest dealing" },
  { name: "Lut", arabic: "لُوطٌ", meaning: "Prophet of Allah, nephew of Ibrahim" },
  { name: "Ayyub", arabic: "أَيُّوبُ", meaning: "The Ever-Returning — Prophet Job, exemplar of patience through trial" },
  { name: "Yunus", arabic: "يُونُسُ", meaning: "Dove — Prophet Jonah, \"Companion of the Whale\"" },
  { name: "Ilyas", arabic: "إِلْيَاسُ", meaning: "Prophet Elijah, who called his people back to worshipping Allah alone" },
  { name: "Dhul-Kifl", arabic: "ذُو الْكِفْلِ", meaning: "The One Given a Double Portion — a Prophet noted for his steadfastness" },

  // --- Companions & family of the Prophet ﷺ ---
  { name: "Abubakar", arabic: "أَبُو بَكْرٍ", meaning: "Father of the Young Camel — the first Caliph, the Prophet's closest companion" },
  { name: "Umar", arabic: "عُمَرُ", meaning: "Long-Lived, Flourishing — the second Caliph, known for justice" },
  { name: "Uthman", arabic: "عُثْمَانُ", meaning: "The third Caliph, known for immense generosity and compiling the Qur'an" },
  { name: "Ali", arabic: "عَلِيٌّ", meaning: "The Exalted, The High One — cousin and son-in-law of the Prophet ﷺ" },
  { name: "Khalid", arabic: "خَالِدٌ", meaning: "Eternal, Immortal — Khalid ibn al-Walid, known as \"the Sword of Allah\"" },
  { name: "Zubayr", arabic: "الزُّبَيْرُ", meaning: "Strong, Powerful — a companion promised Paradise" },
  { name: "Talha", arabic: "طَلْحَةُ", meaning: "A flourishing tree — a companion known for his generosity" },
  { name: "Saad", arabic: "سَعْدٌ", meaning: "Good Fortune, Happiness" },
  { name: "Salman", arabic: "سَلْمَانُ", meaning: "Safe, Secure, Peaceful — Salman al-Farisi, seeker of truth" },
  { name: "Ammar", arabic: "عَمَّارٌ", meaning: "Long-Lived, One Devoted to Worship" },
  { name: "Muadh", arabic: "مُعَاذٌ", meaning: "One Who Seeks Refuge — Muadh ibn Jabal, a leading scholar among the companions" },
  { name: "Anas", arabic: "أَنَسٌ", meaning: "Companionship, Sociability — devoted servant of the Prophet ﷺ" },
  { name: "Jabir", arabic: "جَابِرٌ", meaning: "Comforter, One Who Consoles and Restores" },
  { name: "Bilal", arabic: "بِلَالٌ", meaning: "Moisture, Freshness — Bilal ibn Rabah, the first mu'adhin (caller to prayer)" },
  { name: "Hassan", arabic: "حَسَنٌ", meaning: "Handsome, Good — grandson of the Prophet ﷺ" },
  { name: "Husain", arabic: "حُسَيْنٌ", meaning: "Little Handsome One — grandson of the Prophet ﷺ" },
  { name: "Abbas", arabic: "عَبَّاسٌ", meaning: "Stern, Lion-Hearted — uncle of the Prophet ﷺ" },
  { name: "Khadijah", arabic: "خَدِيجَةُ", meaning: "Early Baby — the Prophet's first wife and the first believer" },
  { name: "Khadeejah", arabic: "خَدِيجَةُ", meaning: "Early Baby — the Prophet's first wife and the first believer" },
  { name: "Aisha", arabic: "عَائِشَةُ", meaning: "She Who Lives, Full of Life — wife of the Prophet ﷺ, a great scholar" },
  { name: "Fatimah", arabic: "فَاطِمَةُ", meaning: "Purified Woman, Daughter of Prophet Muhammad ﷺ" },
  { name: "Fateemah", arabic: "فَاطِمَةُ", meaning: "Purified Woman, Daughter of Prophet Muhammad ﷺ" },
  { name: "Maryam", arabic: "مَرْيَمُ", meaning: "The Beloved — mother of Prophet Isa, honoured throughout the Qur'an" },
  { name: "Zainab", arabic: "زَيْنَبُ", meaning: "Fragrant Flower" },
  { name: "Ruqayyah", arabic: "رُقَيَّةُ", meaning: "Rising, Ascending — daughter of the Prophet ﷺ" },
  { name: "Umm Kulthum", arabic: "أُمُّ كُلْثُومٍ", meaning: "Mother of Kulthum — daughter of the Prophet ﷺ" },
  { name: "Hafsah", arabic: "حَفْصَةُ", meaning: "Young Lioness — wife of the Prophet ﷺ, keeper of the first Qur'anic manuscript" },
  { name: "Hafsat", arabic: "حَفْصَةُ", meaning: "Young Lioness — wife of the Prophet ﷺ, keeper of the first Qur'anic manuscript" },
  { name: "Sawdah", arabic: "سَوْدَةُ", meaning: "Wife of the Prophet ﷺ, known for her generosity" },
  { name: "Safiyyah", arabic: "صَفِيَّةُ", meaning: "Pure, Chosen Friend" },
  { name: "Maymunah", arabic: "مَيْمُونَةُ", meaning: "Blessed, Fortunate" },
  { name: "Juwayriyyah", arabic: "جُوَيْرِيَةُ", meaning: "Young Beautiful Woman" },
  { name: "Asma", arabic: "أَسْمَاءُ", meaning: "Elevated, Precious — daughter of Abu Bakr, \"the one with two belts\"" },
  { name: "Sumayyah", arabic: "سُمَيَّةُ", meaning: "Elevated — the first martyr in the history of Islam" },
  { name: "Zulaikha", arabic: "زُلَيْخَا", meaning: "A name traditionally linked to the account of Prophet Yusuf" },
  { name: "Nusaybah", arabic: "نُسَيْبَةُ", meaning: "Of Noble Lineage — a female companion known for bravery in battle" },
  { name: "Imran", arabic: "عِمْرَانُ", meaning: "Prosperity, Long Life — father of Maryam, honoured with a chapter of the Qur'an" },
  { name: "Balqees", arabic: "بلقيس", meaning: "Beautiful, Wealthy Queen " },
  { name: "Bilqees", arabic: "بلقيس", meaning: "Beautiful, Wealthy Queen " },
  { name: "Bilkis", arabic: "بلقيس", meaning: "Beautiful, Wealthy Queen " },
  { name: "Balikis", arabic: "بلقيس", meaning: "Beautiful, Wealthy Queen " },

  // --- "Servant of Allah" (Abd-) names ---
  { name: "Abdullah", arabic: "عَبْدُ اللّٰهِ", meaning: "Servant of Allah" },
  { name: "Abdulrahman", arabic: "عَبْدُ الرَّحْمَٰنِ", meaning: "Servant of the Most Merciful" },
  { name: "Abdulkareem", arabic: "عَبْدُ الْكَرِيمِ", meaning: "Servant of the Most Generous" },
  { name: "Abdulazeez", arabic: "عَبْدُ الْعَزِيزِ", meaning: "Servant of the Almighty, the Mighty One" },
  { name: "Abdulmalik", arabic: "عَبْدُ الْمَلِكِ", meaning: "Servant of the King" },
  { name: "Abdulwahab", arabic: "عَبْدُ الْوَهَّابِ", meaning: "Servant of the Supreme Bestower" },
  { name: "Abdulhakeem", arabic: "عَبْدُ الْحَكِيمِ", meaning: "Servant of the All-Wise" },
  { name: "Abdulquddus", arabic: "عَبْدُ الْقُدُّوسِ", meaning: "Servant of the Most Holy, the Purest" },
  { name: "Abdulsalam", arabic: "عَبْدُ السَّلَامِ", meaning: "Servant of the Source of Peace" },
  { name: "Abdulmajeed", arabic: "عَبْدُ الْمَجِيدِ", meaning: "Servant of the Glorious, the Most Honourable" },
  { name: "Abdulfattah", arabic: "عَبْدُ الْفَتَّاحِ", meaning: "Servant of the Opener, the Judge Who Grants Victory" },
  { name: "Abdulwarith", arabic: "عَبْدُ الْوَارِثِ", meaning: "Servant of the Ultimate Inheritor of all things" },
  { name: "Abdulnasir", arabic: "عَبْدُ النَّاصِرِ", meaning: "Servant of the Helper, the Granter of Victory" },
  { name: "Abdulmumin", arabic: "عَبْدُ الْمُؤْمِنِ", meaning: "Servant of the Giver of Faith and Security" },
  { name: "Abdulhameed", arabic: "عَبْدُ الْحَمِيدِ", meaning: "Servant of the Praiseworthy One" },
  { name: "Abdulbasit", arabic: "عَبْدُ الْبَاسِطِ", meaning: "Servant of the Extender, the One Who Expands Provision" },
  { name: "Abdulrasheed", arabic: "عَبْدُ الرَّشِيدِ", meaning: "Servant of the Rightly Guided, the Guide to the Right Path" },
  { name: "Abdulganiyy", arabic: "عَبْدُ الْغَنِيِّ", meaning: "Servant of the Wealthy One, the Self-Sufficient" },
  { name: "Abdullateef", arabic: "عَبْدُ اللَّطِيفِ", meaning: "Servant of the Subtle, the Most Gentle" },
  { name: "Abdulwaheed", arabic: "عَبْدُ الْوَاحِدِ", meaning: "Servant of the One, the Only" },
  { name: "Abdulqadir", arabic: "عَبْدُ الْقَادِرِ", meaning: "Servant of the All-Capable, the All-Powerful" },
  { name: "Abdulmuiz", arabic: "عَبْدُ الْمُعِزِّ", meaning: "Servant of the Bestower of Honour" },

  // --- Virtue, attribute & meaning-based names ---
  { name: "Rahma", arabic: "رَحْمَةُ", meaning: "Mercy, Compassion from Allah" },
  { name: "Rahmah", arabic: "رَحْمَةُ", meaning: "Mercy, Compassion from Allah" },
  { name: "Rahmat", arabic: "رَحْمَةُ", meaning: "Mercy, Compassion from Allah" },
  { name: "Rahim", arabic: "رَحِيمٌ", meaning: "Most Merciful, Compassionate" },
  { name: "Raheem", arabic: "رَحِيمٌ", meaning: "Most Merciful, Compassionate" },
  { name: "Kareem", arabic: "كَرِيمٌ", meaning: "Generous, Noble, Honourable" },
  { name: "Karimm", arabic: "كَرِيمٌ", meaning: "Generous, Noble, Honourable" },
  { name: "Azeez", arabic: "عَزِيزٌ", meaning: "Mighty, Cherished, Dear One" },
  { name: "Rasheed", arabic: "رَشِيدٌ", meaning: "Rightly Guided, Mature in Judgment" },
  { name: "Wasiu", arabic: "وَاسِعٌ", meaning: "Vast, Broad, All-Encompassing" },
  { name: "Waheed", arabic: "وَحِيدٌ", meaning: "Unique, One and Only" },
  { name: "Kabir", arabic: "كَبِيرٌ", meaning: "Great, Grand, of High Standing" },
  { name: "Lateef", arabic: "لَطِيفٌ", meaning: "Gentle, Kind, Subtle in Understanding" },
  { name: "Sabir", arabic: "صَابِرٌ", meaning: "Patient, Enduring" },
  { name: "Shakir", arabic: "شَاكِرٌ", meaning: "Thankful, Grateful" },
  { name: "Faisal", arabic: "فَيْصَلٌ", meaning: "Decisive, One Who Judges Rightly" },
  { name: "Tariq", arabic: "طَارِقٌ", meaning: "One Who Knocks at Night, the Morning Star" },
  { name: "Nurudeen", arabic: "نُورُ الدِّينِ", meaning: "Light of the Faith" },
  { name: "Sherifdeen", arabic: "شَرِيفُ الدِّينِ", meaning: "Noble One of the Faith" },
  { name: "Muinudeen", arabic: "مُعِينُ الدِّينِ", meaning: "Helper of the Faith" },
  { name: "Tawfiq", arabic: "تَوْفِيقٌ", meaning: "Divine Success, Guidance Toward What Is Right" },
  { name: "Yaqeen", arabic: "يَقِينٌ", meaning: "Certainty, Sure and Steadfast Faith" },
  { name: "Sabitu", arabic: "ثَابِتٌ", meaning: "Firm, Steadfast, Unwavering" },
  { name: "Tijani", arabic: "تِيجَانِي", meaning: "Crowned — associated with the Tijaniyyah tradition of remembrance" },
  { name: "Jimoh", arabic: "جُمُعَةُ", meaning: "Friday — traditionally given to a boy born on the blessed day of Jumu'ah" },
  { name: "Nur", arabic: "نُورٌ", meaning: "Light" },
  { name: "Huda", arabic: "هُدَى", meaning: "Guidance" },
  { name: "Iman", arabic: "إِيمَانٌ", meaning: "Faith, Belief" },
  { name: "Amal", arabic: "أَمَلٌ", meaning: "Hope" },
  { name: "Yasmin", arabic: "يَاسْمِينُ", meaning: "Jasmine — a fragrant, cherished flower" },
  { name: "Taqwa", arabic: "تَقْوَى", meaning: "God-Consciousness, Piety" },
  { name: "Hanan", arabic: "حَنَانٌ", meaning: "Compassion, Tenderness" },
  { name: "Qudrah", arabic: "قُدْرَةُ", meaning: "Power, Ability — a name reflecting inner strength" },
  { name: "Mansur", arabic: "مَنْصُورٌ", meaning: "Triumphant, Divinely Aided, Victorious" },
  { name: "Habeeb", arabic: "حَبِيبٌ", meaning: "Darling, Beloved, Dear One" },
  { name: "Habeebat", arabic: "حَبِيبَةُ", meaning: "Darling, Beloved, Dear One" },
  { name: "Barakat", arabic: "بَرَكَاتٌ", meaning: "Abundant Blessings, Continuous Prosperity" },
  { name: "Mubarak", arabic: "مُبَارَكٌ", meaning: "Blessed One" },

  // --- Yoruba-Nigerian spellings of common Islamic names ---
  { name: "Rasheedat", arabic: "رَشِيدَةُ", meaning: "Rightly Guided, Mature in Judgment (female form)" },
  { name: "Kabirat", arabic: "كَبِيرَةُ", meaning: "Great, Grand, of High Standing (female form)" },
  { name: "Waheedat", arabic: "وَحِيدَةُ", meaning: "Unique, One and Only (female form)" },
  { name: "Lateefat", arabic: "لَطِيفَةُ", meaning: "Gentle, Kind, Subtle in Understanding (female form)" },
  { name: "Kareemat", arabic: "كَرِيمَةُ", meaning: "Generous, Noble, Honourable (female form)" },
  { name: "Azeezat", arabic: "عَزِيزَةُ", meaning: "Mighty, Cherished, Dear One (female form)" },
  { name: "Azeezah", arabic: "عَزِيزَةُ", meaning: "Mighty, Cherished, Dear One (female form)" },
  { name: "Sekinat", arabic: "سَكِينَةُ", meaning: "Tranquility, Peace of Mind and Heart" },
  { name: "Sherifat", arabic: "شَرِيفَةُ", meaning: "Noble, Honourable Woman" },
  { name: "Sidiqat", arabic: "صِدِّيقَةُ", meaning: "Truthful Woman, One Devoted to Truth" },
  { name: "Rafiat", arabic: "رَفِيعَةُ", meaning: "Exalted, of High Rank" },
  { name: "Muinat", arabic: "مُعِينَةُ", meaning: "Helper, Supporter" },
  { name: "Fauziyat", arabic: "فَوْزِيَّةُ", meaning: "Triumphant, Successful Woman" },
  { name: "Basirat", arabic: "بَصِيرَةُ", meaning: "Insightful, Perceptive" },
  { name: "Hikmat", arabic: "حِكْمَةُ", meaning: "Wisdom" },
  { name: "Alimat", arabic: "عَالِمَةُ", meaning: "Knowledgeable Woman, Scholar" },
  { name: "Fadilat", arabic: "فَاضِلَةُ", meaning: "Virtuous, Excellent Woman" },
  { name: "Muniratu", arabic: "مُنِيرَةُ", meaning: "Illuminating, Radiant, One Who Gives Light" },
  { name: "Tawakkalitu", arabic: "تَوَكَّلْتُ", meaning: "Reliance and Trust in Allah" },
  { name: "Tawakkalt", arabic: "تَوَكَّلْتُ", meaning: "Reliance and Trust in Allah" },
  { name: "Safinat", arabic: "سَفِينَةُ", meaning: "Ship — a vessel of safety, a name of good omen" },
  { name: "Ganiyu", arabic: "عَبْدُ الْغَنِيِّ", meaning: "Servant of the Wealthy One" },
  { name: "Bashir", arabic: "بَشِيرٌ", meaning: "Bringer of Good News" },
  { name: "Aminah", arabic: "آمِنَةُ", meaning: "Trustworthy, Peaceful, Mother of the Prophet ﷺ" },
  { name: "Aminat", arabic: "آمِنَةُ", meaning: "Trustworthy, Peaceful, Mother of the Prophet ﷺ" },
  { name: "Ameenat", arabic: "آمِنَةُ", meaning: "Trustworthy, Peaceful, Mother of the Prophet ﷺ" },
  { name: "Ameenah", arabic: "آمِنَةُ", meaning: "Trustworthy, Peaceful, Mother of the Prophet ﷺ" },
  { name: "Sarah", arabic: "سَارَةُ", meaning: "Princess, Noblewoman" },
  { name: "Salma", arabic: "سَلْمَى", meaning: "Peaceful, Safe" },
  { name: "Salmah", arabic: "سَلْمَى", meaning: "Peaceful, Safe" },
  { name: "Halima", arabic: "حَلِيمَةُ", meaning: "Gentle, Patient" },
  { name: "Haleema", arabic: "حَلِيمَةُ", meaning: "Gentle, Patient" },
  { name: "Haleemah", arabic: "حَلِيمَةُ", meaning: "Gentle, Patient" },
  { name: "Amirah", arabic: "أَمِيرَةُ", meaning: "Princess, Leader" },
  { name: "Ameerah", arabic: "أَمِيرَةُ", meaning: "Princess, Leader" },
  { name: "Zayd", arabic: "زَيْدٌ", meaning: "Abundance, Growth" },
  { name: "Hamza", arabic: "حَمْزَةُ", meaning: "Strong, Steadfast" },
  { name: "Layla", arabic: "لَيْلَى", meaning: "Night, Dark Beauty" },
  { name: "Asiya", arabic: "آسِيَةُ", meaning: "One Who Comforts, Wife of Pharaoh who believed in Allah alone" },
  { name: "Nasir", arabic: "نَاصِرٌ", meaning: "Helper, Protector" },
  { name: "Sadiq", arabic: "صَادِقٌ", meaning: "Truthful, Sincere" },
  { name: "Jamila", arabic: "جَمِيلَةُ", meaning: "Beautiful" },
  { name: "Jameela", arabic: "جَمِيلَةُ", meaning: "Beautiful" },
  { name: "Jameelah", arabic: "جَمِيلَةُ", meaning: "Beautiful" },
];

module.exports = { NAME_DB };
