// Source of truth for the name library. The frontend fetches this
// from GET /api/names so both sides always agree on names + meanings.

const NAME_DB = [
  { name: "Luqman", arabic: "لُقْمَانُ", meaning: "The Wise Man, Blessed with Wisdom" },
  { name: "Fatimah", arabic: "فَاطِمَةُ", meaning: "Purified Woman, Daughter of Prophet Muhammad (SAW)" },
  { name: "Rahma", arabic: "رَحْمَةُ", meaning: "Mercy, Compassion from Allah" },
  { name: "Muhammad", arabic: "مُحَمَّدٌ", meaning: "The Praised One" },
  { name: "Aisha", arabic: "عَائِشَةُ", meaning: "She Who Lives, Full of Life, Prophet Muhammad (SAW)'s lovely wife" },
  { name: "Ibrahim", arabic: "إِبْرَاهِيمُ", meaning: "Father of Nations, the Friend of Allah" },
  { name: "Yusuf", arabic: "يُوسُفُ", meaning: "God Increases, the Beautiful One" },
  { name: "Maryam", arabic: "مَرْيَمُ", meaning: "The Beloved, Mother of Prophet Isa" },
  { name: "Zainab", arabic: "زَيْنَبُ", meaning: "Fragrant Flower" },
  { name: "Khadijah", arabic: "خَدِيجَةُ", meaning: "Early Baby, the First Believer" },
  { name: "Hassan", arabic: "حَسَنٌ", meaning: "Handsome, Good" },
  { name: "Husain", arabic: "حُسَيْنٌ", meaning: "Little Handsome One" },
  { name: "Ridwan", arabic: "رِضْوَانُ", meaning: "Contentment, Divine Pleasure" },
  { name: "Abdullah", arabic: "عَبْدُ اللّٰهِ", meaning: "Servant of Allah" },
  { name: "Aminah", arabic: "آمِنَةُ", meaning: "Trustworthy, Peaceful, Mother of the Prophet (SAW)" },
  { name: "Bilal", arabic: "بِلَالٌ", meaning: "Moisture, Freshness" },
  { name: "Hafsah", arabic: "حَفْصَةُ", meaning: "Young Lioness" },
  { name: "Ismail", arabic: "إِسْمَاعِيلُ", meaning: "God Will Hear" },
  { name: "Umar", arabic: "عُمَرُ", meaning: "Long-Lived, Flourishing" },
  { name: "Ali", arabic: "عَلِيٌّ", meaning: "The Exalted, The High One" },
  { name: "Sumayyah", arabic: "سُمَيَّةُ", meaning: "Elevated, First Martyr of Islam" },
  { name: "Sarah", arabic: "سَارَةُ", meaning: "Princess, Noblewoman" },
  { name: "Yaqub", arabic: "يَعْقُوبُ", meaning: "Supplanter, One Who Follows" },
  { name: "Nuh", arabic: "نُوحٌ", meaning: "Rest, Comfort — the Prophet Noah" },
  { name: "Idris", arabic: "إِدْرِيسُ", meaning: "Studious, Interpreter" },
  { name: "Salma", arabic: "سَلْمَى", meaning: "Peaceful, Safe" },
  { name: "Halima", arabic: "حَلِيمَةُ", meaning: "Gentle, Patient" },
  { name: "Amirah", arabic: "أَمِيرَةُ", meaning: "Princess, Leader" },
  { name: "Zayd", arabic: "زَيْدٌ", meaning: "Abundance, Growth" },
  { name: "Hamza", arabic: "حَمْزَةُ", meaning: "Strong, Steadfast" },
  { name: "Layla", arabic: "لَيْلَى", meaning: "Night, Dark Beauty" },
  { name: "Safiyyah", arabic: "صَفِيَّةُ", meaning: "Pure, Chosen Friend" },
  { name: "Ruqayyah", arabic: "رُقَيَّةُ", meaning: "Rising, Ascending" },
  { name: "Asiya", arabic: "آسِيَةُ", meaning: "One Who Comforts, Wife of Pharaoh" },
  { name: "Musa", arabic: "مُوسَى", meaning: "Drawn Out of Water — the Prophet Moses" },
  { name: "Dawud", arabic: "دَاوُودُ", meaning: "Beloved — the Prophet David" },
  { name: "Sulaiman", arabic: "سُلَيْمَانُ", meaning: "Man of Peace — the Prophet Solomon" },
  { name: "Yahya", arabic: "يَحْيَى", meaning: "God is Gracious — the Prophet John" },
  { name: "Zakariyya", arabic: "زَكَرِيَّا", meaning: "Remembrance of God" },
  { name: "Rahim", arabic: "رَحِيمٌ", meaning: "Most Merciful, Compassionate" },
  { name: "Nasir", arabic: "نَاصِرٌ", meaning: "Helper, Protector" },
  { name: "Sadiq", arabic: "صَادِقٌ", meaning: "Truthful, Sincere" },
  { name: "Jamila", arabic: "جَمِيلَةُ", meaning: "Beautiful" },
  { name: "Bashir", arabic: "بَشِيرٌ", meaning: "Bringer of Good News" },
  { name: "Ganiyu", arabic: "عَبْدُ الْغَنِيِّ", meaning: "Servant of the Wealthy One" },
  { name: "Qudrah", arabic: "قدرة", meaning: "Power, Ability, Capacity of a woman" },
  { name: "Idris", arabic: " إدريس", meaning: "One Who Instructs, Interpreter, Prophet of Allah " },
  { name: "Mansur", arabic: "منصور", meaning: "Triumphant, Aided by Allah, the Victorious one" },
  { name: "Habeebat", arabic: "حبيبة", meaning: "Darling, Beloved, Dear One" },
  { name: "Habeeb", arabic: "حبيب", meaning: "Darling, Beloved, Dear One" },
  { name: "Barakat", arabic: "بَرَكَة", meaning: "Abundant Blessings,continuous prosperity" },
  { name: "Mubarak", arabic: "مبارك", meaning: "Abundant Blessings,continuous prosperity" },
];

module.exports = { NAME_DB };
